In [3]:
%matplotlib inline
import numpy as np
import pandas as pd

#import viz # curriculum example visualizations

np.random.seed(1349)

1.) How likely is it that you roll doubles when rolling two dice?

In [4]:
n_trials = nrows= 10_000
n_dice = ncols= 2
first_roll = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows,ncols)
second_roll = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows,ncols)
doubles = (first_roll == second_roll).mean()

In [10]:
doubles
print(f'The probability to roll doubles is {doubles}')

The probability to roll doubles is 0.1655


2.) If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [6]:
n_trials = nrows = 10_000
n_coins = ncols = 8
result = np.random.choice(['heads', 'tails'], n_trials * n_coins).reshape(nrows,ncols)
heads = (result == 'heads').sum(axis =1)

In [7]:
three_heads = (heads ==3).mean()
three_heads

0.2133

In [17]:
more_than_three_heads = (heads>3).mean()
more_than_three_heads

0.6346

3.) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [20]:
n_trials = nrows = 10_000
n_billboards= ncols= 2
result = np.random.choice(['web', 'ds'], n_trials * n_billboards).reshape(nrows,ncols)
ds_billboard = (result == 'ds').sum(axis=1)

In [22]:
both_ds = (ds_billboard ==2).mean()
both_ds

0.2506

4.) Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [23]:
pt_avg = 3
pt_stdev = 1.5
n_days = 5
n_trials = 10_000


In [32]:
pt_bought = np.random.normal(pt_avg,pt_stdev,size=(n_trials,n_days))
pt_bought
pt_on_friday = 17 - pt_bought.sum(axis =1)
pt_on_friday

array([5.32207204, 9.12089577, 4.57212335, ..., 5.03034064, 7.5970624 ,
       4.70068076])

In [33]:
(pt_on_friday >=1).mean()

0.6216

5.) Compare Heights
Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?

In [36]:
avg_men = 178
stdev_men = 8
n_subjects = 5
n_simulations = 10_000
men_height = np.random.normal(avg_men,stdev_men, size=(n_simulations,n_subjects))
men_height

array([[179.21457118, 170.83403036, 185.47577783, 177.19486435,
        183.25140092],
       [187.54439152, 167.8092371 , 178.36302704, 182.06391606,
        181.3460441 ],
       [185.18837881, 180.19795094, 179.91666301, 191.76191673,
        174.03753009],
       ...,
       [175.34392484, 185.99694598, 182.40608524, 185.51205731,
        170.8509586 ],
       [181.45720746, 191.12848221, 185.09081068, 171.45696695,
        181.06817186],
       [191.80579789, 191.33393245, 178.63155172, 163.50700999,
        175.43627386]])

In [37]:
avg_women = 170
stdev_women = 6
n_subjects = 5
n_simulations = 10_000
women_height = np.random.normal(avg_women,stdev_women, size =(n_simulations,n_subjects))
women_height

array([[157.73263047, 177.31575124, 161.92735257, 171.28412929,
        169.21451429],
       [162.27295319, 172.15739713, 169.48709218, 171.00846748,
        173.236181  ],
       [172.56985064, 177.25095374, 168.04840193, 170.51278453,
        176.01194305],
       ...,
       [165.66641929, 171.95765391, 173.72799382, 173.52256894,
        168.19165895],
       [169.52713363, 175.43949203, 178.65618421, 158.57218726,
        167.22186279],
       [165.61495341, 168.19727735, 176.96206387, 178.98825902,
        178.7842162 ]])

In [38]:
(women_height>men_height).mean()

0.212

6.) When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?


In [39]:
1/250 #chance of fail

0.004

In [40]:
1-(1/250) #chance of success

0.996

In [52]:
result = [1,0]
fifty_successes = np.random.choice(result, size = (10_000,50),p=(.996,.004))
fifty_successes

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [58]:
fifty_successes_prob = fifty_successes.sum(axis=1) 
(fifty_successes_prob ==50).mean()

0.8192

In [59]:
hundred_successes = np.random.choice(result, size = (10_000,100),p=(.996,.004))
hundred_successes

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [60]:
hundred_successes_prob = hundred_successes.sum(axis=1) 
(hundred_successes_prob ==100).mean()

0.6665

 What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [62]:
result = [1,0]
download_error = np.random.choice(result, size = (10_000,150),p=(.996,.004))
fail_prob = download_error.sum(axis=1)
(fail_prob <150).mean()

0.4523

How likely is it that 450 students all download anaconda without an issue?

In [63]:
download_error = np.random.choice(result, size = (10_000,450),p=(.996,.004))
no_issue = download_error.sum(axis=1)
(no_issue ==450).mean()

0.1599

7.) There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [64]:
result=[1,0]
food = np.random.choice(result, size =(10_000,3), p=(.70,.30))
prob_no_food = food.sum(axis=1)
(prob_no_food ==0).mean()

0.0297

How likely is it that a food truck will show up sometime this week?

In [67]:
food_this_week = np.random.choice(result, size =(10_000,7), p=(.70,.30))
prob_food = food.sum(axis=1)
(prob_food >=1).mean()

0.9703

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?


In [70]:
round(1/365,3)

0.003

In [71]:
round(1-(1/365),3)

0.997

In [83]:
result=[1,0]
share_birthday23 = np.random.choice(result,size=(10_000,23), p=(.003,.997))

In [84]:
share_birthday23

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [85]:
share_birthday_23 = share_birthday.sum(axis=1)

In [86]:
(share_birthday_23 >0).mean()

0.0722

In [87]:
share_birthday20= np.random.choice(result,size=(10_000,20), p=(.003,.997))
share_birthday20

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [88]:
share_birthday_20 = share_birthday20.sum(axis=1)

In [89]:
(share_birthday_20 >0).mean()

0.0584

In [90]:
share_birthday40= np.random.choice(result,size=(10_000,40), p=(.003,.997))
share_birthday40

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [91]:
share_birthday_40 = share_birthday40.sum(axis=1)
(share_birthday_40).mean()

0.1209